"""added episodes to anime model

Revision ID: abecb76350bc
Revises: e763cd3cdf6f
Create Date: 2024-10-26 14:03:03.181001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abecb76350bc'
down_revision: Union[str, None] = 'e763cd3cdf6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('episodes', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('shiki_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'shiki_id')
    op.drop_column('anime', 'episodes')
    # ### end Alembic commands ###
