"""added screenshot

Revision ID: af105367e854
Revises: abecb76350bc
Create Date: 2024-11-03 13:38:09.074864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af105367e854'
down_revision: Union[str, None] = 'abecb76350bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('original', sa.String(), nullable=True),
    sa.Column('anime', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anime'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshots_id'), 'screenshots', ['id'], unique=False)
    op.add_column('anime', sa.Column('shiki_url', sa.String(), nullable=True))
    op.add_column('anime', sa.Column('animego_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'animego_url')
    op.drop_column('anime', 'shiki_url')
    op.drop_index(op.f('ix_screenshots_id'), table_name='screenshots')
    op.drop_table('screenshots')
    # ### end Alembic commands ###
